const fs=require('fs'),vm=require('vm'),assert=require('assert');let elements=new Map();let el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',style:{setProperty(){}},dataset:{},open:false,showModal(){this.open=true},close(){this.open=false}});return elements.get(id)};const ctx={document:{getElementById:el},performance:{now:()=>ctx.now||0},clearInterval(){},setInterval:fn=>{ctx.tick=fn;return 1},console,Intl,Math,setTimeout:fn=>{fn();return 0},clearTimeout(){},alert(){}};vm.createContext(ctx);vm.runInContext(fs.readFileSync('dist/game.js','utf8'),ctx);const result=vm.runInContext(`(async()=>{
function fixture(){buildBoard(4);S={players:colors.slice(0,4).map((c,i)=>({id:i,name:'P'+i,ai:false,cash:1500,pos:0,jail:0,jailed:false,card:0,out:false})),turn:0,round:1,mode:'classic',level:'normal',speed:180,parking:false,pot:0,phase:'roll',dice:[3,4],doubles:0,extra:false,log:[],debt:null,auction:null,winner:null};tiles.forEach(t=>{t.owner=null;t.h=0;t.m=false});paused=false;busy=false;$('modal').open=false}
fixture();cur().pos=1;S.phase='buy';buy();if(tiles[1].owner!==0||cur().cash!==1440)throw Error('buy');tiles[3].owner=0;if(rent(tiles[1])!==4)throw Error('monopoly');if(!canBuild(tiles[1]))throw Error('build');tiles[1].h=1;if(!canBuild(tiles[1]))throw Error('first visit cap');if(rent(tiles[1])!==10)throw Error('rent');
fixture();cur().pos=39;await move(2);if(cur().cash!==1700||cur().pos!==1||S.phase!=='buy')throw Error('pass go');
fixture();tiles[5].owner=1;tiles[15].owner=1;if(rent(tiles[5])!==50)throw Error('station');tiles[12].owner=1;if(rent(tiles[12])!==28)throw Error('utility');
fixture();cur().cash=10;charge(100,1);if(S.phase!=='debt')throw Error('debt');cur().cash=120;settle();if(cur().cash!==20||S.players[1].cash!==1600)throw Error('settle');
fixture();cur().pos=1;S.phase='buy';auction();submitSecretBid(100000);submitSecretBid(0);submitSecretBid(0);await submitSecretBid(0);continueAuction();finishAuctionBuild(0);if(tiles[1].owner!==0||cur().cash!==1490||S.phase!=='end')throw Error('auction');
fixture();jail();if(!cur().jailed||cur().pos!==10||S.extra)throw Error('jail');release();if(cur().cash!==1450||cur().jailed)throw Error('release');
fixture();S.players[2].out=true;S.players[3].out=true;charge(2000,1);bankrupt();if(S.winner!==1)throw Error('bankruptcy');
fixture();S.mode='quick';S.round=20;S.turn=3;S.turnsInRound=3;S.phase='end';end();if(S.winner===null||S.round!==21)throw Error('limit');
fixture();tiles[5].owner=0;tiles[12].owner=0;if(worth(cur())!==1850||fmt(worth(cur()))!=='18.500.000 ₫')throw Error('non-land asset total');
let seen=[];const originalRender=render;render=()=>{if(moving)seen.push(cur().pos);originalRender()};cur().pos=38;await move(3);if(seen.join(',')!=='39,0,1'||cur().cash!==1700)throw Error('visible steps');
for(const mode of ['classic','quick','custom']){for(let i=0;i<4;i++){$('n'+i).value='P'+i;$('p'+i).value='human'}$('mode').value=mode;$('initial').value='30000000';$('duration').value='0';$('level').value='normal';$('speed').value='650';$('parking').checked=false;start();if(S.players.some(p=>p.cash!==3000))throw Error('starting money '+mode)}
let prior=S;$('initial').value='123';start();if(S!==prior)throw Error('invalid capital mutated state');
for(const type of ['chance','chest']){fixture();const deck=cardDeck(type);if(deck.length!==32||new Set(deck.map(c=>c.id)).size!==32)throw Error('catalogue');let idsSeen=new Set(Array.from({length:32},()=>drawCard(type).id));if(idsSeen.size!==32||S.decks[type].length)throw Error('shuffle without repeat');if(!drawCard(type))throw Error('reshuffle');for(const c of deck){fixture();cur().pos=5;tiles[1].owner=0;tiles[1].h=2;S.decks={[type]:[c]};let before=cur().cash;await card(type);if(c.effect==='reward'&&cur().cash!==before+c.amount)throw Error('reward '+c.id);if(c.effect==='fee'&&cur().cash!==before-c.amount)throw Error('fee '+c.id);if(c.effect==='percentReward'&&Math.abs(cur().cash-before*(1+c.rate))>1e-6)throw Error('percent reward '+c.id);if(c.effect==='percentFee'&&Math.abs(cur().cash-before*(1-c.rate))>1e-6)throw Error('percent fee '+c.id);if(c.effect==='repair'&&cur().cash!==before-2*c.house)throw Error('repair '+c.id);if(c.effect==='catchup'&&cur().cash!==before+c.high)throw Error('catchup');if(c.effect==='assetReward'&&cur().cash!==before+c.per)throw Error('asset reward');if(c.effect==='release'&&cur().card!==1)throw Error('release');if(c.effect==='shield'&&cur().rentShield!==(c.qty||1))throw Error('rent shield');if(c.effect==='taxshield'&&cur().taxShield!==(c.qty||1))throw Error('tax shield');if(c.effect==='feeshield'&&cur().feeShield!==(c.qty||1))throw Error('fee shield');if(c.effect==='extra'&&!S.extra)throw Error('extra');}}
if(cardDeck('chance').some(c=>cardDeck('chest').some(k=>k.title===c.title)))throw Error('same card titles');
fixture();tiles[1].owner=1;cur().pos=1;await land();let beforeCash=cur().cash,sellerCash=S.players[1].cash;let q=buyoutQuote(tiles[1]);buyout();if(tiles[1].owner!==0||cur().cash!==beforeCash-q.total||S.players[1].cash!==sellerCash+q.sellerAmount)throw Error('buyout money');if(!(buyoutQuote(tiles[1]).premium>q.premium))throw Error('buyout escalation');
fixture();tiles[1].owner=1;tiles[3].owner=1;tiles[1].h=1;tiles[3].h=1;cur().pos=1;S.phase='end';q=buyoutQuote(tiles[1]);if(q.value!==110||q.premium!==2.05)throw Error('building/monopoly premium');buyout();if(tiles[1].h!==0||tiles[3].h!==1)throw Error('buyout building treatment');
fixture();tiles[1].owner=1;tiles[1].h=5;cur().pos=1;S.phase='end';buyout();if(tiles[1].owner!==1)throw Error('hotel protected');
fixture();tiles[5].owner=1;tiles[5].m=true;cur().pos=5;S.phase='end';q=buyoutQuote(tiles[5]);buyout();if(tiles[5].owner!==0||tiles[5].m||q.redemption!==110)throw Error('mortgaged takeover');
fixture();tiles[1].owner=1;cur().pos=1;S.phase='end';cur().cash=1;buyout();if(tiles[1].owner!==1||cur().cash!==1)throw Error('cannot afford');
fixture();cur().rentShield=1;tiles[1].owner=1;cur().pos=1;await land();if(cur().cash!==1500||cur().rentShield)throw Error('rent immunity');cur().taxShield=1;cur().pos=4;await land();if(cur().cash!==1500||cur().taxShield)throw Error('tax immunity');cur().feeShield=1;eventFee(100);if(cur().cash!==1500||cur().feeShield)throw Error('fee immunity');
for(const count of [2,3,4,5,6,7,8]){for(let i=0;i<8;i++){$('n'+i).value='P'+i;$('p'+i).value='human'}$('initial').value='15000000';$('playercount').value=String(count);start();if(S.players.length!==count||tiles.length!==boardSize(count))throw Error('size '+count);const positions=new Set(tiles.map(t=>coords(t.i).join(',')));if(positions.size!==tiles.length)throw Error('board coordinates');const edge=tiles.length/4+1;for(const t of tiles){const [r,c]=coords(t.i);if(r<1||c<1||r>edge||c>edge||![1,edge].includes(r)&&![1,edge].includes(c))throw Error('perimeter');if(t.type==='land'&&(!ids[t.g].includes(t.i)||!Number.isFinite(rent(t))))throw Error('group/rent')}if(roleIndex('jail')!==tiles.length/4||roleIndex('parking')!==tiles.length/2||roleIndex('gojail')!==tiles.length*3/4)throw Error('corners');S.turn=count-1;S.turnsInRound=count-1;S.phase='end';end();if(S.turn!==0||S.round!==2)throw Error('8 turn wrap');S.players[0].pos=1;S.phase='buy';auction();submitSecretBid(100000);for(let n=1;n<count;n++)await submitSecretBid(0);continueAuction();finishAuctionBuild(0);if(tiles[1].owner!==0)throw Error('large auction');S.phase='roll';cur().pos=tiles.length-1;let before=cur().cash;await move(2,{resolve:false});if(cur().pos!==1||cur().cash!==before+200)throw Error('expanded wrap');await move(-3,{resolve:false});if(cur().pos!==tiles.length-2||cur().cash!==before+200)throw Error('expanded backwards');S.phase='roll';const other=count-1;let cash0=cur().cash,cashOther=S.players[other].cash;executeTrade(other,1,-1,10,0);if(tiles[1].owner!==other||cur().cash!==cash0-10||S.players[other].cash!==cashOther+10)throw Error('expanded trade');let dest=cardDeck('chance')[5].destination;if(tiles[dest].baseId!==24)throw Error('dynamic card destination');S.phase='roll';cur().pos=roleIndex('gojail');await land();if(cur().pos!==roleIndex('jail')||!cur().jailed)throw Error('dynamic jail');const tax=tiles.find(t=>t.type==='tax'&&t.taxRate===.1);for(const cash of [0,1,100,1500,5000]){cur().cash=cash;cur().pos=tax.i;let expected=cash-taxAmount(tax,cash);await land();if(Math.abs(cur().cash-expected)>1e-8||S.phase==='debt')throw Error('proportional tax');}for(const taxTile of tiles.filter(t=>t.type==='tax'))if(taxAmount(taxTile,100)!==(taxTile.taxRate===.1?10:5))throw Error('tax rates');}
$('playercount').value='8';$('initial').value='15000000';for(let i=0;i<8;i++){$('n'+i).value='P'+i;$('p'+i).value='human'}let savedRandom=Math.random;for(let first=0;first<8;first++){Math.random=()=> (first+.25)/8;start();if(S.turn!==first)throw Error('random starter');for(let step=0;step<8;step++){S.phase='end';end();if(step<7&&S.round!==1)throw Error('premature round');}if(S.round!==2||S.turn!==first)throw Error('random round accounting');}Math.random=savedRandom;
fixture();cur().pos=1;S.phase='buy';buy(3);if(tiles[1].h!==3||cur().cash!==1290||canBuild(tiles[1]))throw Error('3-house purchase cap');S.phase='end';upgradeHere();if(tiles[1].h!==3)throw Error('blocked early 4');await land();if(tiles[1].visits!==1||canBuild(tiles[1]))throw Error('same turn revisit');S.turnSerial=1;await land();if(tiles[1].visits!==2||!canBuild(tiles[1]))throw Error('next visit unlock 4');upgradeHere();if(tiles[1].h!==4||canBuild(tiles[1]))throw Error('hotel locked visit2');S.turnSerial=2;await land();upgradeHere();if(tiles[1].h!==5||canBuild(tiles[1]))throw Error('hotel on visit3');
fixture();cur().pos=1;S.phase='buy';buy(4);if(tiles[1].owner!==null)throw Error('invalid package');cur().cash=100;buy(3);if(tiles[1].owner!==null)throw Error('unaffordable package');
fixture();cur().pos=1;S.phase='buy';buy(1);cur().pos=3;S.phase='end';if(canBuild(tiles[1]))throw Error('remote building');cur().pos=1;tiles[1].m=true;if(canBuild(tiles[1]))throw Error('mortgaged building');
for(const amount of ['5000000','30000000','100000000']){$('playercount').value='4';$('initial').value=amount;for(let i=0;i<4;i++){$('n'+i).value='P'+i;$('p'+i).value='human'}start();rules();if(!$('modalbody').innerHTML.includes(fmt(Number(amount)/10000)))throw Error('dynamic initial rules');closeModal();}
fixture();cur().pos=1;S.phase='buy';auction();let rows=[{id:0,bid:1},{id:1,bid:99},{id:2,bid:0}];if(pickWeighted(rows,0)!==0||pickWeighted(rows,.009)!==0||pickWeighted(rows,.01)!==1||pickWeighted(rows,.999)!==1||pickWeighted([{id:0,bid:0}],0)!==null)throw Error('weighted 1 percent');
if(submitSecretBid(20000000)!==false||Object.keys(S.auction.bids).length)throw Error('excess bid');submitSecretBid(10000);if(cur().cash!==1500||$('actions').innerHTML.includes('Giá hiện tại'))throw Error('bid reservation secrecy');submitSecretBid(990000);submitSecretBid(0);let originalRand=Math.random;Math.random=()=>.005;await submitSecretBid(0);Math.random=originalRand;if(S.auction.winner!==0||cur().cash!==1499||S.players[1].cash!==1500)throw Error('small bid can win only winner charged');continueAuction();finishAuctionBuild(3);if(tiles[1].h!==3||cur().cash!==1349)throw Error('lottery house package');
fixture();cur().pos=1;S.phase='buy';auction();for(let i=0;i<4;i++)await submitSecretBid(0);if(S.auction.winner!==null||tiles[1].owner!==null||cur().cash!==1500)throw Error('zero bids');continueAuction();if(S.phase!=='end')throw Error('zero finish');
fixture();cur().pos=1;tiles[1].owner=1;tiles[1].h=1;S.phase='buy';auction();if(S.auction!==null)throw Error('no auction built land');
fixture();S.players[2].cash=2000;S.players[3].out=true;let order=rankedPlayers().map(p=>p.id);if(order[0]!==2||order.at(-1)!==3||S.players[0].id!==0||S.turn!==0)throw Error('ranking stable identities');S.players[0].cash=2500;render();if(rankedPlayers()[0].id!==0||!$('players').innerHTML.includes('#1'))throw Error('ranking updates');
fixture();cur().pos=1;S.phase='buy';cur().cash=0;skipPurchase();if(S.phase!=='end'||S.auction!==null||tiles[1].owner!==null||cur().cash!==0)throw Error('skip with zero cash');fixture();cur().pos=1;S.phase='buy';S.extra=true;skipPurchase();if(!S.extra||cur().cash!==1500||S.phase!=='end')throw Error('optional skip preserves extra turn');fixture();cur().pos=1;S.phase='buy';auction();$('secretbid').value='1.000.000';previewSecretBid();if(parseBidInput('1.000.000')!==1000000||$('lockbid').disabled||!$('bidpreview').textContent.includes('1.000.000 ₫'))throw Error('visible formatted bid');if(!Number.isNaN(parseBidInput('-10000'))||!Number.isNaN(parseBidInput('1.5'))||!Number.isNaN(parseBidInput('')))throw Error('invalid input');$('secretbid').value='999999999';previewSecretBid();if(!$('lockbid').disabled)throw Error('oversized bid lock');
$('playercount').value='4';fixture();S.timeLimit=900000;S.timeLeft=900000;startClock();paused=true;
})()`,ctx);result.then(()=>{ctx.now=60000;ctx.tick();assert.strictEqual(vm.runInContext('S.timeLeft',ctx),900000);vm.runInContext('paused=false',ctx);ctx.now=120000;ctx.tick();assert.strictEqual(vm.runInContext('S.timeLeft',ctx),840000);vm.runInContext('S.timeLeft=100;S.debt={amount:500,to:1};S.players[1].cash=1600',ctx);ctx.now=121000;ctx.tick();assert.strictEqual(vm.runInContext('S.winner',ctx),1);assert.strictEqual(vm.runInContext('S.timeLeft',ctx),0);console.log('Passed: purchase, monopoly, even building, rent, start payment, rail/utilities, debt, auction, jail, bankruptcy, round limit, non-land totals, animated steps, timer pause, timeout ranking, starting money in every mode, card catalogue effects, 2–8 players, board perimeter/group integrity, expanded auctions/cards/jail, proportional taxes, random starters and rounds, 64 card effects and shuffle, buyout premiums/transfer/hotel lock, shields, staged house visits and packages, dynamic initial-money rules, secret weighted auction, zero/invalid bids, winner-only payment, house choice, live ranking, skip without auction, readable bid formatting and validation.');}).catch(e=>{console.error(e);process.exitCode=1});
