'use strict';
let announcementQueue=[],announcementTimer=null,announcementUntil=0;
function resetAnnouncements(){clearTimeout(announcementTimer);announcementQueue=[];announcementUntil=0;if(typeof window!=='undefined')$('milestonetoast').hidden=true;}
function announce(title,message,id){if(typeof window==='undefined')return;announcementQueue.push({title,message,id,epoch});if(!announcementUntil)showNextAnnouncement();}
function showNextAnnouncement(){const item=announcementQueue.shift();if(!item){announcementUntil=0;$('milestonetoast').hidden=true;drive();return;}if(item.epoch!==epoch){showNextAnnouncement();return;}const box=$('milestonetoast');box.hidden=false;box.style.setProperty('--notice-color',colors[item.id]||'#63e6b5');box.innerHTML='<b>'+esc(item.title)+'</b><span>'+esc(item.message)+'</span>';announcementUntil=Date.now()+4000;clearTimeout(announcementTimer);announcementTimer=setTimeout(showNextAnnouncement,4000);drive();}
function regionSets(){return Object.values(ids).filter(a=>a.length);}
function goalProgress(p){const owned=own(p).filter(t=>!t.m),regions=regionSets().filter(a=>a.every(i=>tiles[i].owner===p.id&&!tiles[i].m)).length,hotels=new Set(owned.filter(t=>t.h===5).map(t=>t.g)).size;return {regions,hotels,laps:p.laps||0,explored:(p.explored||[]).length};}
function qualifyingGoal(p){if(p.out||(p.blockedUntilLap||0)>(p.laps||0))return null;const g=goalProgress(p);return g.regions>=3?'Ba vùng trọn bộ':g.hotels>=2?'Hai vùng khách sạn':g.laps>=explorationTarget().laps&&g.explored>=explorationTarget().tiles?'Nhà khám phá':null;}
function monitorMilestones(){if(!S?.goalMode||S.winner!==null)return;const snapshot={};for(const t of tiles.filter(t=>t.owner!==null&&t.h===5))snapshot['hotel:'+t.i]={id:t.owner,title:'Khách sạn mới!',message:S.players[t.owner].name+' xây khách sạn tại '+t.name+'.'};for(const a of regionSets()){let id=tiles[a[0]].owner;if(id!==null&&a.every(i=>tiles[i].owner===id&&!tiles[i].m))snapshot['region:'+tiles[a[0]].g]={id,title:'Đã sở hữu trọn một vùng!',message:S.players[id].name+' gom đủ '+a.map(i=>tiles[i].name).join(', ')+'.'};}for(let side=0;side<4;side++){let a=tiles.filter(t=>t.type==='land'&&Math.floor(t.i/(tiles.length/4))===side),id=a[0]?.owner;if(id!==null&&id!==undefined&&a.every(t=>t.owner===id&&!t.m))snapshot['side:'+side]={id,title:'Một dãy đã đổi chủ!',message:S.players[id].name+' sở hữu toàn bộ đất ở cạnh '+(side+1)+' của bàn cờ.'};}if(S.milestoneSnapshot)for(const [key,item] of Object.entries(snapshot))if(S.milestoneSnapshot[key]?.id!==item.id){log(item.message);announce(item.title,item.message,item.id);}S.milestoneSnapshot=snapshot;S.pendingGoals=S.pendingGoals||{};for(const p of S.players){const goal=qualifyingGoal(p),pending=S.pendingGoals[p.id];if(pending&&(!goal||pending.goal!==goal)){delete S.pendingGoals[p.id];log(p.name+' mất điều kiện thắng mục tiêu.');}if(goal&&!S.pendingGoals[p.id]){S.pendingGoals[p.id]={goal,waiting:S.players.filter(o=>!o.out&&o.id!==p.id).map(o=>o.id)};log(p.name+' đạt '+goal+'! Đối thủ còn một lượt để phản công.');announce('CẢNH BÁO THẮNG MỤC TIÊU',p.name+' đạt '+goal+'. Mỗi đối thủ còn một lượt để ngăn chặn!',p.id);}}}
function advanceGoalWindow(completedId){if(!S?.goalMode||S.winner!==null)return;monitorMilestones();for(const [id,q] of Object.entries(S.pendingGoals||{})){q.waiting=q.waiting.filter(n=>n!==completedId&&!S.players[n].out);if(Number(id)===S.turn&&!q.waiting.length&&qualifyingGoal(S.players[id])===q.goal){S.winner=Number(id);S.winReason=q.goal;log(S.players[id].name+' thắng ngay bằng '+q.goal+', không xét ai giàu nhất.');announce('CHIẾN THẮNG!',S.players[id].name+' hoàn thành '+q.goal+'.',Number(id));clearInterval(clockInterval);break;}}}
function recordLap(p){if(!S.goalMode)return;p.laps=(p.laps||0)+1;const alive=S.players.filter(o=>!o.out),min=Math.min(...alive.map(worth)),max=Math.max(...alive.map(worth));if(S.round>=2&&worth(p)===min&&min<max&&!p.rentShield){p.rentShield=1;log(p.name+' nhận lá chắn lật kèo: miễn một lần thuê, vì đang có ít tổng tài sản nhất.');announce('CƠ HỘI LẬT KÈO',p.name+' nhận miễn một lần thuê khi qua Xuất phát.',p.id);}}
function challengeGoal(id){if(!valid('end')||cur().challengeUsed||id===S.turn||!S.pendingGoals?.[id])return;const defender=cur(),target=S.players[id];defender.challengeUsed=true;target.blockedUntilLap=(target.laps||0)+1;delete S.pendingGoals[id];log(defender.name+' phản công '+target.name+': mục tiêu bị khóa đến khi người đó qua Xuất phát lần nữa.');announce('PHẢN CÔNG!',defender.name+' chặn mục tiêu của '+target.name+' đến lần qua Xuất phát tiếp theo.',defender.id);render();drive();}
function goalThreatMarkup(p,disabled){if(!S.goalMode||S.winner!==null)return '';let rows=Object.entries(S.pendingGoals||{});if(!rows.length)return '<button class="goal-link" onclick="showGoals()">Xem mục tiêu thắng & tiến độ</button>';return '<div class="goal-threat"><b>⚑ Cảnh báo thắng ngay</b>'+rows.map(([id,q])=>'<p>'+esc(S.players[id].name)+' · '+q.goal+' · còn '+q.waiting.filter(n=>!S.players[n].out).length+' đối thủ cần kết thúc lượt</p>'+ (Number(id)!==p.id&&S.phase==='end'?'<button onclick="challengeGoal('+id+')" '+(disabled||p.challengeUsed?'disabled':'')+'>Phản công miễn phí'+(p.challengeUsed?' · đã dùng':' · 1 lần/ván')+'</button>':'')).join('')+'<button onclick="showGoals()">Xem mục tiêu</button></div>';}
function goalRulesMarkup(){return '<h3>Thắng mục tiêu & lật kèo</h3><p>Đạt một trong ba mục tiêu: sở hữu đủ 3 bộ màu; có khách sạn ở 2 bộ màu khác nhau; hoặc qua Xuất phát '+explorationTarget().laps+' lần và thực sự dừng ở '+explorationTarget().tiles+' ô đất khác nhau (không cần mua). Máy và người áp dụng cùng luật.</p><p>Đạt mục tiêu mới chỉ bật cảnh báo. Mỗi đối thủ còn một lượt bình thường; nếu vẫn giữ điều kiện khi lượt quay về, bạn thắng ngay, không xét tổng tài sản. Lượt gieo thêm không rút ngắn cửa sổ này. Mua lại, giao dịch, bán nhà có thể phá điều kiện sở hữu.</p><p>Mỗi người có 1 lần Phản công miễn phí trong cả ván, dùng cuối lượt để khóa mục tiêu của đối thủ đến khi họ qua Xuất phát lần nữa. Không lấy mất đất hoặc khách sạn. Nếu đang có tổng tài sản thấp nhất, từ vòng 2, qua Xuất phát được 1 lá chắn miễn thuê khi chưa có lá chắn; không tích lũy. Cảnh báo khách sạn, đủ vùng và đủ dãy xuất hiện 4 giây.</p>';}
function showGoals(){modal('<button class="close" onclick="closeModal()">✕</button><h2>Mục tiêu thắng ngay</h2>'+goalRulesMarkup()+(S?S.players.filter(p=>!p.out).map(p=>{const g=goalProgress(p);return '<div class="asset"><b>'+esc(p.name)+'</b><p>Vùng đủ bộ: '+g.regions+'/3 · Vùng có khách sạn: '+g.hotels+'/2<br>Khám phá: '+g.laps+'/'+explorationTarget().laps+' lần Xuất phát + '+g.explored+'/'+explorationTarget().tiles+' ô đất<br>Phản công: '+(p.challengeUsed?'Đã dùng':'Còn 1 lần')+((p.blockedUntilLap||0)>g.laps?' · Mục tiêu đang bị khóa':'')+'</p></div>';}).join(''):''));}
